# "org" ensures this Service is used with the correct Serverless Framework License Key.
org: mangotest
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auction-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - ${file(src/iam/AuctionsTableIAM.yml):AuctionsTableIAM}
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}

functions:
  createAuction:
    handler: src/handlers/auctions/create.handler
    events:
      - httpApi: 'POST /auctions'
  getAuctions:
    handler: src/handlers/auctions/get.handler
    events:
      - httpApi: 'GET /auctions'
  getAuctionById:
    handler: src/handlers/auctions/getById.handler
    events:
      - httpApi: 'GET /auctions/{id}'
  placeBid:
    handler: src/handlers/auctions/placeBid.handler
    events:
      - httpApi: 'PATCH /auctions/{id}/bid'
  processAuctions:
    handler: src/handlers/auctions/process.handler

resources:
  Resources:
    AuctionsTable: ${file(src/resources/AuctionsTable.yml):AuctionsTable}

custom:
  AuctionsTable:
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn

package:
  individually: true
